# originally from https://github.com/jimmybish/qnap-docker-compose/

services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - TZ=Europe/Lisbon
    volumes:
      - /share/Container/nzbget:/config
      - /share/Downloads/NZBGet:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
    networks:
      qnet-static:
        ipv4_address: 192.168.1.1
  
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - TZ=Europe/Lisbon
    volumes:
      - /share/Container/radarr:/config
      - /share/Multimedia/Movies:/movies
      - /share/Downloads/NZBGet/completed/Movies:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      qnet-static:
        ipv4_address: 192.168.1.2

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - TZ=Europe/Lisbon
    volumes:
      - /share/Container/sonarr:/config
      - /share/Multimedia/TV:/tv
      - /share/Downloads/NZBGet/completed/TV:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      qnet-static:
        ipv4_address: 192.168.1.3

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    environment:
      - VERSION=docker
    volumes:
      - /share/Container/plex:/config
      - /share/Multimedia/TV:/tv
      - /share/Multimedia/Movies:/movies
      - /share/Multimedia/Photos:/photos
      - /share/Backups/plex_db:/db_backups
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    networks:
      qnet-static:
        ipv4_address: 192.168.1.4

  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    environment:
      - TZ=Europe/Lisbon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /share/Container/portainer:/data
    ports:
      - 9000:9000
      - 8000:8000
    restart: unless-stopped
    networks:
      qnet-static:
        ipv4_address: 192.168.1.5

  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: homeassistant
    environment:
      - TZ=Europe/Lisbon
    volumes:
      - /share/Container/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    networks:
      qnet-static:
        ipv4_address: 192.168.1.6

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    volumes:
      - /share/Container/adguardhome/workdir:/opt/adguardhome/work
      - /share/Container/adguardhome/confdir:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      qnet-static:
        ipv4_address: 192.168.1.7

  nginx-proxy-manager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    volumes:
      - /share/Container/nginx-proxy-manager/data:/data
      - /share/Container/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - /share/Container/nginx-proxy-manager/tmp:/tmp
    ports:
      - 80:80
      - 81:81
      - 443:443
    restart: unless-stopped
    networks:
      qnet-static:
        ipv4_address: 192.168.1.8

networks:
  qnet-static:
    driver: qnet
    driver_opts:
      iface: "eth1"
    ipam:
      driver: qnet
      options:
        iface: "eth1"
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254
